### ISSUE TITLE
执行过程中报错 SSLError

### ISSUE THREAD

**Issue by IanSmith123** [IanSmith123/ucas-covid19#14]
```
等待3秒后填报
等待2秒后填报
等待1秒后填报
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.ucas.ac.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sub.py", line 150, in <module>
    report(username=user, ***
  File "./sub.py", line 144, in report
    login(s, username, password)
  File "./sub.py", line 36, in login
    r = s.post("https://app.ucas.ac.cn/uc/wap/login/check", data=payload)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='app.ucas.ac.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
Error: Process completed with exit code 1.
```

解决方案：
不验证证书。
bug已经修复，merge上游代码即可。

**Comment by IanSmith123** [comment]
如果不会merge操作，可以删掉原来fork的仓库重新fork本仓库，然后按照 [方法二](https://github.com/IanSmith123/ucas-covid19#%E6%96%B9%E6%B3%95%E4%BA%8C-%E4%BD%BF%E7%94%A8-github-actions%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8) 重新操作一次即可。
