### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by IanSmith123** [IanSmith123/ucas-covid19#18]
```
等待3秒后填报
等待2秒后填报
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f468a59ae48>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.ucas.ac.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f468a59ae48>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sub.py", line 154, in <module>
    report(username=user, ***
  File "./sub.py", line 148, in report
    login(s, username, password)
  File "./sub.py", line 39, in login
    r = s.post("https://app.ucas.ac.cn/uc/wap/login/check", data=payload)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='app.ucas.ac.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f468a59ae48>: Failed to establish a new connection: [Errno 110] Connection timed out',))
等待1秒后填报
Error: Process completed with exit code 1.
```
极少出现此问题，暂不打算修复（最近比较忙，欢迎PR）

**Comment by IanSmith123** [comment]
近期暂未收到该bug的报告，此 issue 关闭。
